### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by puneetimpinge** [tzmartin/Ti-Amazon-S3#7]
I have tried to upload image to aws s3 server, first time its properly uploaded to s3 but second time I got 400 Bad request error and its not uploaded to s3.

Below are the error messages:

[ERROR] :  TiHTTPClient: (TiHttpClient-2) [222,128527] HTTP Error (java.io.IOException): 400 : Bad Request
[ERROR] :  TiHTTPClient: java.io.IOException: 400 : Bad Request
[ERROR] :  TiHTTPClient: 	at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1227)
[ERROR] :  TiHTTPClient: 	at java.lang.Thread.run(Thread.java:841)

Please help me to solve the above issue.

I used 
titanium sdk 5.3.0
Anddroid version 4.4.4

I got above issue for android device only. On iOS its properly works.

**Comment by jazzparty** [comment]
I have same problem.
It's not solved yet?

**Comment by Sophrinix** [comment]
this problem is solved and was solved at the time you asked this question. amazon is very sensitive to time and timezone formatting issues. I might consider doing a tutorial on this module.

**Comment by obaidjawad** [comment]
Here is the solution. You might probably using only one global xhr object 

`Alloy.Globals.xhr=Titanium.Network.createHTTPClient({async:true});`

In Android I figured out that for every WCF/service request you need to initialize a new xhr object and send the request. This will work smoothly.

I'm doing many projects on appcelerator my email is obaidjawad1@gmail.com.

**Comment by ghost** [comment]
[ERROR] :  TiHTTPClient: (TiHttpClient-1) [0,228025] HTTP Error (java.io.IOException): 400 : Bad Request
[INFO] :   400
[ERROR] :  TiHTTPClient: java.io.IOException: 400 : Bad Request
[ERROR] :  TiHTTPClient: 	at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1283)
[ERROR] :  TiHTTPClient: 	at java.lang.Thread.run(Thread.java:764)
[INFO] :   Aborting HTTP client
